# Question 1:

In [19]:
import numpy as np

In [20]:
# Matrices
A = np.array([[1, 4, 1], [-2, 2, 1], [3, 1, 4]])
B = np.array([[3, 1, 2], [1, 5, 6], [2, 1, 2]])

# Vectors
x = np.array([1, 2, 3])
y = np.array([0, 1, 0])

### (a)

In [21]:
a_hk = 3 * x + 2 * y
a_hk

array([3, 8, 9])

### (b)

In [22]:
b_hk = np.dot(A, x)
b_hk

array([12,  5, 17])

### (c)

In [23]:
c_hk = np.dot(A, B)
c_hk

array([[ 9, 22, 28],
       [-2,  9, 10],
       [18, 12, 20]])

### (d)

In [24]:
d_hk = np.linalg.norm(x)
d_hk

3.7416573867739413

### (e)

In [25]:
e_hk = np.linalg.norm(y)
e_hk

1.0

### (f)

In [26]:
f_hk = np.dot(x, y)
f_hk

2

### (g)

In [27]:
cos_theta_for = f_hk / (d_hk * e_hk)
theta_value = np.arccos(cos_theta_for)
theta_degree = np.degrees(theta_value)  # Convert to degrees
theta_degree

57.688466762576155

# Question 6:

In [28]:
import numpy as np

In [29]:
# Powers -> P and temperatures -> T from the table
P = np.array([[10, 10, 10], 
              [100, 10, 10], 
              [10, 100, 10], 
              [10, 10, 100]])

T = np.array([[21, 23], 
              [47, 35], 
              [39, 47], 
              [32, 53]])


In [30]:
# Add a column of ones to P for the intercept (affine part)
P_affine = np.hstack([P, np.ones((P.shape[0], 1))])

coef, residuals, rank, s = np.linalg.lstsq(P_affine, T, rcond=None)

coef


array([[ 0.28888889,  0.13333333],
       [ 0.2       ,  0.26666667],
       [ 0.12222222,  0.33333333],
       [14.88888889, 15.66666667]])

In [31]:
# respective Coefficients for T1 and T2 as a function of P1, P2, P3, using coef respectively
coef_T1 = coef[:, 0]
coef_T2 = coef[:, 1]

# Here, I am Solving for p -> such that -> [ T1 <= 65 and T2 <= 65 ]
max_p_T1 = (65 - coef_T1[3]) / (coef_T1[0] + coef_T1[1] + coef_T1[2])
max_p_T2 = (65 - coef_T2[3]) / (coef_T2[0] + coef_T2[1] + coef_T2[2])

# The maximum p is the smaller of the two values , So I have used min to get the minimum of the 2 values
max_p = min(max_p_T1, max_p_T2)
max_p


67.27272727272722